name: Build

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        id: build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.build.outputs.build-output }}
          archive: false

  release:
    name: Release
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          path: out

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          files: out/**/*.geode
